### ISSUE TITLE
rdf-ucr NOTE repo should be added to the common rdf-star README.md

### ISSUE THREAD

**Issue by TallTed** [w3c/rdf-ucr#11]
- [ ] [RDF 1.2 NOTEs](https://github.com/w3c/rdf-ucr#rdf-12-notes) section should then be parallel to the [RDF 1.2 recommendations](https://github.com/w3c/rdf-ucr#rdf-12-recommendations) 
- [ ] [rdf-ucr](https://github.com/w3c/rdf-ucr) note should be listed in [RDF 1.2 NOTEs](https://github.com/w3c/rdf-ucr#rdf-12-notes) section
- [ ] Any other RDF 1.2 Notes should be added to the [RDF 1.2 NOTEs](https://github.com/w3c/rdf-ucr#rdf-12-notes) section
- [ ] Common README.md should be updated across all RDF 1.2 & SPARQL 1.2 repos

**Comment by pfps** [comment]
I do not believe that there has been a decision to publish the UCR document as a note.

**Comment by TallTed** [comment]
@pfps — I do not believe there has been a decision to *NOT* publish the UCR document as a note.

This is a [repo for the UCR document](https://github.com/w3c/rdf-ucr), which is being worked on by members of the [RDF-star WG](https://www.w3.org/groups/wg/rdf-star).

This document is certainly not on the REC track, but it doesn't make much sense to me to work on it at all, if it's purely ephemeral. To my mind, that puts it on the NOTE track.

If you've a different categorization you feel is better, that's fine. This repo should still be cross-linked to/from the repos for the other docs being worked on by the RDF-star WG, and that is the crux of [this issue](https://github.com/w3c/rdf-ucr/issues/11).

**Comment by pfps** [comment]
@TallTed So the question is how to mention this repository given the current state.   I don't want to say that there will be a WG note, or even that there is a document.   Perhaps the best solution is to make it a separate category in the list of WG results, neither a recommendation or a note, with this repository as the only member, and later change the category to WG note if the WG so decides.  Something to discuss on the WG call today, I guess.
