### ISSUE TITLE
Use case "RELEVEN STructured Assertion Record model"

### ISSUE THREAD

**Issue by akuckartz** [w3c/rdf-ucr#7]
This non-trivial use case is work in progress.

Re-Evaluating the Eleventh Century with Linked Events and Entities
Tara Andrews (@tla), Carla Ebel, Nina Richards (@NinaBrundke)
Linked Pasts 7, Ghent (online), 16.12.2021
[Presentation, 73 pages]
https://ucloud.univie.ac.at/index.php/s/jhJ60pyadwDmPg8

Page 10:
> Digital Humanities/LOD:
– While LOD triples are useful to most researchers, historians work with conflicting ideas
– Factoids, stored as triples, too positivistic
– Need to capture data beyond factoids

Page 11:
> Aim: develop and test new ways how digital data about historical phenomena can be created and curated
● Aim: find a way to map conflicting data
● -> make data most helpful and usable for historians
● By using the STAR model

Page 13:
> **ST**ructured **A**ssertion **R**ecord model
● As modified LOD model
● Subject, predicate, object
● Source: primary source material/provenance
● Authority: Scholar who interprets the source

Page 14:
> It allows to make assertions
● Link subject, predicate and object to sources and authorities
● The authority of one assertion can be the subject of another assertion
● → different views can be mapped, visualized, exported

**Comment by pfps** [comment]
@tla @NinaBrundke

The working group has officially decided to collect new use cases and enhance existing one.   The need described here appears to be very suitable as a use case for the group.  

Who should be contacted to find out more about this use case?   Alternatively you or someone else can create a Use Case issue in this repository by clicking on the New Issue link above.   Someone from the working group will be assigned to the use case to help turn it into something that can be used to guide the technical work of the group.

**Comment by tla** [comment]
Hi @pfps - Great, and many thanks for your interest! I am probably the best contact point right now; I'll try to make a use case issue as soon as possible.

**Comment by pfps** [comment]
@tla  Thanks.   The process that the group will be using is still being working on.  See https://github.com/w3c/rdf-ucr for a short description.   The basic idea is to describe representation, querying, and reasoning requirements for your use case so that they can guide the working group and be checked against the final recommendation.  Discussion on the use case will occur in the use case issue and there will also be a separate document or wiki entry with a clean description of the use case.

**Comment by akuckartz** [comment]
This issue is replaced by #12
